### ISSUE TITLE
Drop plugins references

### ISSUE THREAD

**Issue by sebbASF** [apache/httpd-site#3]
https://github.com/apache/httpd-site/blob/6668f26f52ff94936fc1b0f57aa23f208857141a/pelicanconf.yaml#L11

It looks like the plugins section can be dropped, and so can theme/plugins.

c.f. www-site which does not have either of these anymore

**Comment by sebbASF** [comment]
I tried a local Docker build without them, and it appeared to work fine

**Comment by gstein** [comment]
Fixed. Thanks!
